### ISSUE TITLE
[BUG] Sound playing on startup

### ISSUE THREAD

**Issue by Satanarious** [ashpynov/PlayniteSound#15]
**Describe the bug**
Even after having the `Skip first 'select' sound on startup` option checked in the Playnite Sounds Mod's addon settings. The sound still plays on each launch. I have to manually go into the game description and pause the sound from the sound controls at the bottom.

**To Reproduce**
I have the startpage addon, so that you know, and I have to click Playnite out of focus to pause the sound and sometimes even that doesn't work.

**Expected behavior**
The last selected game page's sound should not play on startup

**Additional context**
Also after startup, playnite's extensions load various processes and maybe download things in the foreground, like the steam tags extension, HowLongToBeat and more......

**Comment by ashpynov** [comment]
https://github.com/ashpynov/PlayniteSound/releases/tag/v5.7.16

**Comment by Satanarious** [comment]
Thank you, the issue is now fixed.
