### ISSUE TITLE
[BUG] Sound playing on hovering startpage's games

### ISSUE THREAD

**Issue by Satanarious** [ashpynov/PlayniteSound#16]
**Describe the bug**
I have the startpage addon installed and eveytime I hover over a game on the page, the playnite sound for the last selected game starts playing, and then I have to manually pause the sound by going into the game's description page and pausing using the sound controls at the bottom.

**To Reproduce**
1. Install the startpage addon
2. Hover over any game from the game shelves
3. This should unpause the sound for the last selected game in the game list/grid.

**Expected behavior**
The sound should not play during any interaction but only when you are on the game list/grid page with the description open. It should only be played and unpaused using sound controls.

**Additional context**

**Comment by ashpynov** [comment]
Could you please check desired behavior at https://github.com/ashpynov/PlayniteSound/releases/tag/v5.7.16 as soon as sound like it may be fixed buy new option to play only when Library is active

**Comment by Satanarious** [comment]
Thank you. The latest update fixed this issue. Well done.
