### ISSUE TITLE
[Feature Request/Enhancement] Expanded Music Formats

### ISSUE THREAD

**Issue by sunsetHue** [ashpynov/PlayniteSound#4]
**Is your feature request related to a problem? Please describe.**
Current support is limited by the lousy and high-compression .mp3 or the uncommon size-inefficient .wav format. A lot of original game music is distributed in the loseless .flac format and storage-efficient low-compression .ogg. You need to convert these files to their older comparisons to use them. 

Edit: .wav cannot be used for music either. It functions only as a sound effect format with the reverse being accurate too currently.

**Describe the solution you'd like**
Support for greater range of audio formats.

**Describe alternatives you've considered**
Converting all files to .mp3 or .wav is a working solution. Besides the problems highlighted above, the audio playback still functions properly.

**Additional context**
I submit this issue fully aware this is a volunteer-run fork of the original extension. If it isn't possible to do this right now or isn't planned, the current addon works fine as is. **I appreciate the work done to continue to support it.**

**Comment by ashpynov** [comment]
You may use ogg without any problem as background music for game- just put it into \ExtraMetadata\Games\game-guid\Music Files

**Comment by sunsetHue** [comment]
**.wav and .flac can be selected and play now.**

.ogg files can be selected and added but do not play any audio. No related errors in the playnite.log or extensions.log

**Comment by ld892012** [comment]
I have the same problem with ogg files, I have tried various conversion options without any success.

**Comment by ld892012** [comment]
According to [this page](https://support.microsoft.com/en-us/topic/file-types-supported-by-windows-media-player-32d9998e-dc8f-af54-7ba1-e996f74375d9), `ogg` files don't appear in supported formats for `MediaPlayer` function, but `wma` files does, this can be a good compromise between storage and quality
