### ISSUE TITLE
[BUG] Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by felipecustodio** [ashpynov/PlayniteSound#8]
**Describe the bug**

When downloading music for multiple games at the same time, without manually selecting, this error pops up. I checked and the 'Source' is filled for all selected games.

**To Reproduce**
1. Go to Library
2. Select multiple games
3. Right click, Playnite Sounds, Download, All

**Expected behavior**
Download music automatically for given list, skip errors if multiple items are selected, and send error notification later (for example, Failed for 10 items, check logs)

**Screenshots**

![image](https://github.com/user-attachments/assets/70082c9b-5b22-46dc-9989-d1ccf60f1931)

**Additional context**
This issue was happening in a previous version, and the issue was closed

**Comment by ashpynov** [comment]
Please try 5.7.11

**Comment by felipecustodio** [comment]
Hi @ashpynov, thanks for replying! 
It downloaded the first song successfully, but failed on the second:
![image](https://github.com/user-attachments/assets/2f87aff7-2ca1-4b54-92f6-c1fefd13a2f0)

If you need additional details, let me know.

**Comment by LuckyBeepo** [comment]
i am having the same issue, how can I provide the log to you I'm unfamiliar with how to get it

**Comment by LuckyBeepo** [comment]
[playnite.log](https://github.com/user-attachments/files/17454567/playnite.log)
i think i got it

**Comment by LuckyBeepo** [comment]
I noticed it seems to happen only with youtube not khinsider

**Comment by felipecustodio** [comment]
Hi @ashpynov,

This is the error that occurs now with the updated extension:

```
28-10 03:36:47.964|INFO |PlayniteSounds#PlayniteSounds:Starting album search for game 'Kingdom Hearts HD 1.5 + 2.5 ReMIX'
28-10 03:36:49.903|INFO |PlayniteSounds#PlayniteSounds:Selected album 'Kingdom Hearts HD 1.5/2.5 ReMIX Soundtrack' from source 'Youtube' for game 'Kingdom Hearts HD 1.5 + 2.5 ReMIX'
28-10 03:36:50.899|INFO |PlayniteSounds#PlayniteSounds:Found songs for album 'Kingdom Hearts HD 1.5/2.5 ReMIX Soundtrack' of game 'Kingdom Hearts HD 1.5 + 2.5 ReMIX'
28-10 03:36:50.899|ERROR|PlayniteSounds#PlayniteSounds:   at PlayniteSounds.PlayniteSounds.DownloadSongsFromGame(GlobalProgressActionArgs args, String progressTitle, Source source, Game game, String gameDirectory, Boolean songSelect, Boolean albumSelect, Boolean overwrite)
   at PlayniteSounds.PlayniteSounds.StartDownload(GlobalProgressActionArgs args, List`1 games, Source source, String progressTitle, Boolean albumSelect, Boolean songSelect, Boolean overwrite)
   at PlayniteSounds.PlayniteSounds.<>c__DisplayClass139_1.<CreateDownloadDialogue>b__1()
   at PlayniteSounds.PlayniteSounds.Try(Action action)
System.NullReferenceException: Object reference not set to an instance of an object.
   at PlayniteSounds.PlayniteSounds.DownloadSongsFromGame(GlobalProgressActionArgs args, String progressTitle, Source source, Game game, String gameDirectory, Boolean songSelect, Boolean albumSelect, Boolean overwrite)
   at PlayniteSounds.PlayniteSounds.StartDownload(GlobalProgressActionArgs args, List`1 games, Source source, String progressTitle, Boolean albumSelect, Boolean songSelect, Boolean overwrite)
   at PlayniteSounds.PlayniteSounds.<>c__DisplayClass139_1.<CreateDownloadDialogue>b__1()
   at PlayniteSounds.PlayniteSounds.Try(Action action)
```

The following error message is displayed:

![image](https://github.com/user-attachments/assets/9b923de9-ce84-4700-9a0f-47d18b4737ff)

This was done by selecting multiple games, asking to download music for all, without overwriting existing music, and from all sources (Insider + Youtube).

Some songs downloaded properly, until this game. The game's library is Epic Games.

**Comment by ashpynov** [comment]
Well it help to find one more place. check v5.7.13 please

**Comment by felipecustodio** [comment]
Looks stable to me now @ashpynov, I'm currently downloading songs for my entire library, so far no more errors, I'll follow up when it's finished =)

**Comment by felipecustodio** [comment]
Hi @ashpynov, ran with no issues on my end, thank you!
